Article:
    fields:
        title: varchar(50)
        content: text
    relations:
        Category: one
        Tag: many

Category:
    fields:
        title: varchar(50)
    relations:
        Article: many

Tag:
    fields:
        name: varchar
    relations:
        Article: many
